// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEM2gjNcW6t7hqPXF21AbgEUlwYfQZI-I',
    appId: '1:159489236703:web:80d0a2d6a5f5ce017f936a',
    messagingSenderId: '159489236703',
    projectId: 'iot-incubator-91ebb',
    authDomain: 'iot-incubator-91ebb.firebaseapp.com',
    databaseURL: 'https://iot-incubator-91ebb-default-rtdb.firebaseio.com',
    storageBucket: 'iot-incubator-91ebb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2trlNF1Sz8m4xqKGX1c9wlAmxS0xegp8',
    appId: '1:159489236703:android:876e9a796956ed637f936a',
    messagingSenderId: '159489236703',
    projectId: 'iot-incubator-91ebb',
    databaseURL: 'https://iot-incubator-91ebb-default-rtdb.firebaseio.com',
    storageBucket: 'iot-incubator-91ebb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI8qbgCtW0YPUc9SNgR2JMWSgpIa7tXXE',
    appId: '1:159489236703:ios:4f77341905be0a4f7f936a',
    messagingSenderId: '159489236703',
    projectId: 'iot-incubator-91ebb',
    databaseURL: 'https://iot-incubator-91ebb-default-rtdb.firebaseio.com',
    storageBucket: 'iot-incubator-91ebb.firebasestorage.app',
    iosBundleId: 'com.example.iotAppy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI8qbgCtW0YPUc9SNgR2JMWSgpIa7tXXE',
    appId: '1:159489236703:ios:4f77341905be0a4f7f936a',
    messagingSenderId: '159489236703',
    projectId: 'iot-incubator-91ebb',
    databaseURL: 'https://iot-incubator-91ebb-default-rtdb.firebaseio.com',
    storageBucket: 'iot-incubator-91ebb.firebasestorage.app',
    iosBundleId: 'com.example.iotAppy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEM2gjNcW6t7hqPXF21AbgEUlwYfQZI-I',
    appId: '1:159489236703:web:99e7cefcfb6539337f936a',
    messagingSenderId: '159489236703',
    projectId: 'iot-incubator-91ebb',
    authDomain: 'iot-incubator-91ebb.firebaseapp.com',
    databaseURL: 'https://iot-incubator-91ebb-default-rtdb.firebaseio.com',
    storageBucket: 'iot-incubator-91ebb.firebasestorage.app',
  );
}
